#GUIA DEFINITIVA PYTHON 00

"""

HISTORIA QUE NO LE IMPORTA A NADIE:
    -PYTHON FUE CREADO POR GUIDO VAN ROSSUM A FINES DE LA DECADA DE 1980 EN PAISES BAJOS. GUIDO BUSCABA UN LENGUAJE DE PROGRAMACION FACIL DE APRENDER Y LEER,
    QUE FUERA EFICIENTE Y PERMITIERA UNA RAPIDA ITERACION EN EL DESARROLLO DE SOFTWARE.
    -EL NOMBRE FUE INSPIRADO POR LA AFICION AL GRUPO HUMORISTICO MONTY PYTHON
    -EN 1991 FUE PUBLICADO POR PRIMERA VEZ EN LA COMUNIDAD DE USENET
    -EN 2000 SE LANZO LA VERSION 2.O DE PYTHON, QUE INCLUYO MEJORAS SIGNIFICATIVAS EN EL LENGUAJE Y EN SU BIBLIOTECA ESTANDAR
    -EN 2008 SE LANZO LA VERSION 3.0 DE PYTHON Y SE HA IDO ADAPTANDO GRADUALMENTE A LOS NUEVOS SISTEMAS
    -ACTUALMENTE ES UNO DE LOS LENGUAJES DE PROGRAMACION MAS POPULARES Y AMPLIAMENTE UTILIZADOS EN LA INDUSTRIA DEL SOFTWARE.

CARACTERISTICAS PRINCIPALES DE PYTHON:
    1.SINTAXIS SENCILLA Y LEGIBLE: SU DISEÑO SE BASA EN EL USO DE ESPACIOS EN BLANCO, NO UTILIZA {} NI ; COMO OTROS LENGUAJES COMO C,C++ O JAVA.
    2.INTERPRETADO: NO REQUIERE DE UN PROCESO DE COMPILACION EXPLICITO, SE EJECUTAN DIRECTAMENTE POR EL INTERPRETE DE PYTHON (POR EJEMPLO EN C++ HABRIA QUE HACER G++ ARCHIVOS -O NOMBRE_EJECUTABLE).
    3.MULTIPARADIGMA: ES UN LENGUAJE MULTIPARADIGMA QUE PERMITE PROGRAMACION IMPERATIVA, ORIENTADA A OBJETOS Y FUNCIONAL.
    4.TIPADO DINAMICO. LAS VARIABLES NO TIENEN QUE ESTAR ASOCIADAS A UN TIPO ESPECIFICO, SI NO QUE VAN COGIENDO ESE VALOR CON EL CURSO DE LA EJECUCION(EN C++ O JAVA SERIA STRING S = "").
    5.AMPLIA BIBLIOTECA ESTANDAR: PYTHON VIENE CON UNA AMPLIA BIBLIOTECA QUE PROPORCIONA MODULOS Y FUNCIONES, COMO ACCESO A BASES DE DATOS, CREACION DE INTERFACES...
    6.PORTABILIDAD: ES UN LENGUAJE PORTATIL, LO QUE SIGNIFICA QUE LOS PROGRAMAS ESCRITOS EN PYTHON PUEDEN EJECUTARSE EN DIFERENTES PLATAFORMAS SIN CAMBIOS SIGNIFICATIVOS.
    7.ORIENTACION A OBJETOS: ADMITE LA PROGRAMACION ORIENTADA A OBJETOS Y CON ELLO, TODAS SUS PROPIEDADES INTRINSECAS COMO ENCAPSULACION, HERENCIA Y POLIMORFISMO.
    8. EXTENSIBILIDAD: PUEDE EXTENDERSE MEDIANTE INTEGRACION DE MODULOS Y BIBLIOTECAS ESCRTIAS EN OTROS LENGUAJES COMO C O C++, ESTO PERMITE APROVECHAR LA VELOCIDAD Y EFICIENCIA DE LENGUAJES DE BAJO NIVEL.

COMENTARIOS: SE PUEDEN PONER CON # PARA UNA SOLA LÍNEA O """ """/''' ''' PARA VARIAS
    '''                                  
    ESTE ES UN COMENTARIO
    EN VARIAS 
    LINEAS
    '''
SE PODRIA HACER IGUAL CON """ """    

ESTA GUIA SE ESTA REALIZANDO CON LA ULTIMA VERSION DE PYTHON DISPONIBLE 3.11.4
ENLACE PARA LA DOCUMENTACION OFICIAL:
https://docs.python.org/3.11/tutorial/index.html
    
"""










