"""
EN ESTA SECCION VEREMOS LOS PRINCIPALES TIPOS DE DATOS, NO CONFUNDIR CON LAS VARIABLES(ESTE ASPECTO SE TRATARA MAS ADELANTE)
"""

#TIPO INT (NUMEROS ENTEROS SIN PARTE DECIMAL)
print(type(1))

#TIPO FLOAT (NUMEROS EN PUNTO FLOTANTE)
print(type(1.5))

#STRING (SON CADENAS DE CARACTERES)
#SE PUEDE PONER CON COMILLA DOBLE O SIMPLE COMO QUERAMOS
print(type("1"))
print(type('HOLA QUE TAL'))

#BOOL (REPRESENTA EL ESTADO DE VERDAD, TRUE/FALSE)
print(type(True))

#LISTAS (SON SECUENCIAS ORDENADAS Y MUTABLES DE ELEMENTOS. PUEDEN CONTENER CUALQUIER TIPO DE DATOS, INCLUSO OTROS TIPOS DE DATOS)
v = [1,2,3,4]
v2 = [1,2,"3",True]
print(type(v))
print(type(v2))

#TUPLAS
#CONJUNTOS 
#DICCIONARIOS