"""
SECCION DEDICADA A LOS STRINGS(CADENAS DE TEXTO)
"""
#FUNCIONES DE STRING QUE PUEDEN SER UTILES
my_string = "Mi variable string"

#LEN() DEVUELVE LA LONGITUD DE UN STRING
print(len(my_string))

#LOWER() DEVUELVE LA CADENA EN MINUSCULA
print(my_string.lower())

#UPPER() DEVUELVE LA CADENA EN MAYUSCULA
print(my_string.upper())

#SPLT(SEPARADOR) DEVUELVE SUBCADENAS SEPARADAS POR UNA LETRA O SIMBOLO(PUEDE SER MUY UTIL PARA ANALIZAR CADENAS, YA QUE PODEMOS SEPARAR POR ESPACIOS)
ejemplo = "Devuelveme cada palabra separada por espacios"
print(ejemplo.split(" "))

#REPLACE(OLD, NEW) DEVUELVE LA CAEDNA CAMBIANDO LAS OCURRENCIAS DE OLD, POR LAS DE NEW
ejemplo2 = "Quiero cambiar todas las a por E mayuscula"
print(ejemplo.replace("a","E"))

#FUNCIONES QUE DEVUELVEN TRUE O FALSE
print(ejemplo.isalpha())#TODOS LOS CARACTERES DE LA CADENA SON LETRAS
print(ejemplo.isdigit())#TODOS LOS CARACTERES DE LA CADENA SON DIGITOS
print(ejemplo.islower())#TODOS LOS CARACTERES DE LA CADENA ESTAN EN MINUSCULA

my_other_string = "Mi otra variable string"
print(my_string + " " + my_other_string)#PODEMOS CONCATENAR STRINGS CON EL OPERADOR +

#PARA CONCATENAR UN STRING CON MUCHAS VARIABLES PODEMOS HACERLO CON EL OPERADOR + O CON .FORMAR()
nombre, apellido, edad = "Alberto", "Canovas", "22"#ATENTOS AQUÍ PORQUE ESTAMOS DECLARANDO 22 COMO STRING, PERO SI LO DECLARARAMOS COMO INT, HABRÍA QUE CASTEARLO EN EL PRINT
print("Mi nombre es " + nombre + " " + apellido + " y mi edad es de " + edad)#ESTO FUNCIONA Y ES CORRECTO, PERO ES UNA MALA PRÁCTICA
edad2 = 22
#print("Mi nombre es " + nombre + " " + apellido + " y mi edad es de " + edad2)#ESTO DA ERROR PORQUE PRINT IMPRIME STRING Y EDAD2 ES UN INT, TENEMOS QUE PASARLO A STRING
print("Mi nombre es " + nombre + " " + apellido + " y mi edad es de " + str(edad2))#ESTO DA ERROR PORQUE PRINT IMPRIME STRING Y EDAD2 ES UN INT, TENEMOS QUE PASARLO A STRING

#PORQUE HAY QUE ESTAR PONIENDO LOS ESPACIOS Y LOS + TODO EL RATO 

#LA FORMA CORRECTA Y DE BUENAS PRÁCTICAS ES
#CON LA FUNCION FORMAT Y AÑADIENDO LOS {}, VAMOS A IR SUSTITUYENDO POR CADA {} LAS VARIABLES DE FORMAT
print("Mi nombre es {} {} y mi edad es de {}".format(nombre, apellido, edad))
#OTRA FORMA MUY BUENA ES, LA F DEL PRINCPIO HACE DE INFERENCIA Y SACA EL VALOR DE CADA VARIABLE COMO SE DECLARA
print(f"Mi nombre es {nombre} {apellido} y mi edad es de {edad}")

#PODEMOS ACCEDER A UN CARACTER DE UN STRING CON EL OPERADOR [POS], LAS POSICIONES VAN DESDE 0 QUE ES LA PRIMERA HASTA LEN -1 QUE ES LA ULTIMA
cadena = "python"
print(cadena[0])#MUESTRA LA P
print(cadena[len(cadena)-1])#MUESTRA LA N
print(cadena[3])#MUESTRA LA H

#PARA RECORRER UN STRING, SE USAN BUCLES O LOOPS QUE VEREMOS EN FUTURAS SECCIONES, PERO EL ACCESO POR CARACTER SE REALIZA ASÍ CON EL [] DESDE 0 HASTA N-1; SIENDO N = LEN

#HAY INFINITUD DE FUNCIONES CON STRINGS, ESTAS SON ALGUNAS DE LAS MÁS BÁSICAS PARA COMENZAR