"""
EN PYTHON, UN CONJUNTO (SET) ES UNA COLECCIÓN DESORDENADA DE ELEMENTOS ÚNICO Y MUTABLES. LOS CONJUNTOS SON UTILIZADOS CUANDO NECESITAS
ALMACENAR ELEMENTOS SIN UN ORDEN ESPECIFICO Y ASEGURARTE DE QUE NO HAYA DUPLICADOS
LAS PRINCIPALES CARACTERISTICAS DE ESTAS SON:
    1. ELEMENTOS UNICOS: LOS CONJUNTOS NO PUEDEN OBTENER ELEMENTOS DUPLICADOS. SI INTENTAS AGREGAR UN ELEMENTO DUPLICADO AL CONJUNTO, SE IGNORARÁ
    2. DESORDENADOS: LOS CONJUNTOS NO MANTIENEN UN ORDEN ESPECIFICO DE LOS ELEMENTOS, POR LO QUE NO PUEDES ACCEDER A LOS ELEMENTOS MEDIANTE UN INDICE
    3. MUTABLES: LOS CONJUNTOS SON MUTABLES, LO QUE SIGNIFICA QUE PUEDEN AGREGAR Y ELIMINAR ELEMENTOS DESPUÉS DE SU CRACIÓN.
    4. COLECCIONES DE ELEMENTOS HETEROGÉNEOS: LOS CONJUNTOS PUEDEN CONTENER ELEMENTOS DE DIFERENTES TIPOS COMO ENTEROS, CADENAS, TUPLAS U OTROS CONJUNTOS

"""

#PARA CREAR UN CONJUNTO USAMOS {} O LA FUNCION SET
my_conjunto = {1,2,3}
my_conjunto2 = set([2,3,4])
print(type(my_conjunto))
print(my_conjunto2)

#PODEMOS AÑADIR ELEMENTOS A UN CONJUNTO CON LA FUNCION ADD
my_conjunto.add(4)
print(my_conjunto)
#SI INTENTO AÑADIR OTRA VEZ EL 4
my_conjunto.add(4)
print(my_conjunto)#COMO VEMOS EN LA SALIDA NO HACE NADA

#PODEMOS ELIMINAR ELEMENTOS DE MI CONJUNTO CON LA FUNCION REMOVE O DISCARD, AMBOS REALIZAN LA ACCION DE ELIMINAR UN ELEMENTOS LA DIFERENCIA ES:
#QUE SI USAMOS REMOVE EN UN ELEMENTOS QUE NO EXISTE, GENERA UN ERROR KEYERROR, SIN EMBARGO, EL DISCARD IGNORA LA ACCION Y NO SUCEDE NADA
my_conjunto.remove(1)
print(my_conjunto)
my_conjunto.discard(2)
print(my_conjunto)

#PODEMOS VERIFICAR SI UN CONJUNTO CONTIENE UN ELEMENTO CON LA FUNCION IN QUE DEVUELVE UN BOOLEANO
print(2 in my_conjunto)
print(3 in my_conjunto)

#LOS CONJUNTOS TIENEN OPERACIONES ESPECIALES PROPIAS COMO UNION, INTERSECCIÓN Y DIFERENCIA: 
set1 = {1, 2, 3}
set2 = {3, 4, 5}
union = set1.union(set2)
print(union)
interseccion = set1.intersection(set2)
print(interseccion)
diferencia = set1.difference(set2)
print(diferencia)

#PARA VACIAR NUESTRO CONJUNTO
my_conjunto.clear()

#PARA ELIMINAR UN CONJUNTO 
del my_conjunto

#SI QUEREMOS OBTENER UNA ESTRUCTURA ORDENADA A PARTIR DE UN CONJUNTO / SET DEBEMOS CASTEAR. PERO NO SABEMOS EL OREN EN EL QUE SE VA A GUARDAR, SI NOS FIJAMOS METEMOS 
#PRIMERO LAS LETRAS Y AL IMPRIMIRLO SALE 1-2-3-C-B-A
my_conjunto3 = {'a','b','c',1,2,3}
my_lista_aux = list(my_conjunto3)
print(my_lista_aux)
print(type(my_lista_aux))