"""
UN DICCIONARIO ES UNA ESTRUCTURA DE DATOS QUE ALMACENA PARES DE CLAVE-VALOR. ES SIMILAR A UN DICCIONARIO DE PALABRAS DONDE CADA PALABRA (CLAVE) TIENE UN SIGNIFICADO
(VALOR) ASOCIADO. LOS DICCIONARIOS SON ÚTILES CUANDO NECESITAS ALMACENAR Y RECUPERAR VALORES BASADOS EN UNA CLAVE EN LUGAR DE UN ÍNDICE NUMERICO. ESTO ES LO MISMO 
QUE LOS HASH MAP EN JAVA, CONJUNTO DE CLAVE-VALOR ÚNICOS. UN EJEMPLO MUY CLARO ES PODEMOS USAR DNI PARA RECUPERAR UN OBJETO PERSONA
"""
my_diccionario0 = dict()
my_diccionario = {}
print(type(my_diccionario))
my_diccionario1 = {"1": "Felipe", "2" : "Eugenio", "3" : 21}#DENTRO DE UN DICCIONARIO PODEMOS TENER OTRO DICCIONARIO, UNA LISTA, UN SET... OTRA ESTRUCTURA DE DATOS
print(my_diccionario1)

#PARA ACCEDER A UN ELEMENTO DE UN DICCIONARIO DEBEMOS BUSCARLO POR SU CLAVE Y ESTE NOS RETORNARA EL VALOR
print(my_diccionario1["1"])
#TAMBIEN SE PUEDE HACER CON EL METODO GET
print(my_diccionario1.get("2"))
#LA FUNCION KEYS DEVUELVE UNA LISTA CON TODAS LAS CLAVES DEL DICCIONARIO
my_list = my_diccionario1.keys()
print(my_list)
#LA FUNCIONES VALUES DEVUELVE UNA LISTA CON TODOS LOS VALORES DEL DICCIONARIO
my_list1 = my_diccionario1.values()
print(my_list1)

#PARA AÑADIR Y MODIFICAR ELEMENTOS AL DICCIONARIO USAMOS
my_diccionario1["4"] = "Roquefeler"#ESTO FUNCIONARA SIEMPRE Y CUANDO NO HAYA YA UNA CLAVE CON ESE VALOR, SI ESTA REPETIDA MOFICARA EL VALOR
print(my_diccionario1)
my_diccionario1["4"] = "CASTELL DE FEILS"
print(my_diccionario1)#ESTO MODIFICA EL VALOR DE LA CLAVE 4

#PARA ELIMINAR ELEMENTOS DE UN DICCIONARIO
del my_diccionario1["1"]#ELIMINAMOS LA CLAVE 1 Y SU VALOR ASIGNADO
print(my_diccionario1)
my_diccionario1.pop("2")#ELIMINA LA CLAVE Y DEVUELVE EL VALOR ASOCIADO A ESA CLAVE
print(my_diccionario1)

my_diccionario1.clear()#ESTO BORRA POR COMPLETO TODOS LOS PARES CLAVE-VALOR DEL DICCIONARIO
print(my_diccionario1)

#PARA VER SI UN UNA CLAVE - VALOR EXISTE EN EL DICCIONARIO TENEMOS QUE HACER: 
print(2 in my_diccionario1)#TENEMOS QUE BUSCAR LA CLAVE 



