"""
EN PYTHON, LAS CLASES SON UNA FORMA DE DEFINIR OBJETOS QUE TIENEN PROPIEDAD Y MÉTODOS ASOCIADOS. PROPORCIONAN UNA ESTRUCTURA PARA ORGANIZAR
Y MANIPULAR DATOS DE MANERA EFICIENTE. UNA CLASE ES COMO UN PLANO O UNA PLANTILLA QUE DEFINE LAS CARACTERÍSTICAS Y EL COMPORTAMIENTO DE UN OBJETO,
Y LOS OBJETOS SON INSTANCIAS DE UNA CLASE
POR CONVENCIÓN LOS NOMBRES DE LAS CLASES EN PYTHON SE PONEN EN CamelCase COMENZANDO POR LETRAS MAYUSCULAS.
EJEMPLOS DE ESTO SERÍAN: MiClase // MiClaseEjemplo

ESTO ES UNA INTRODUCCIÓN AL PARADIGMA DE PROGRAMACIÓN ORIENTADA A OBJETOS, ESTE ES UN TEMA MUY AMPLIO Y COMPLEJO QUE NO SE EXPLICA EN PROFUNDIDA AQUÍ
SI NO QUE SE VERÁ EN LECCIONES SIGUIENTES. LA INTENCIÓN DE ESTA CLASE ES SABER QUE ES UNA CLASE, COMO DEFINIR UNA CLASE, CREAR UN CONSTRUCTOR CON UNOS ATRIBUTOS 
Y SABER QUE SE PUEDEN DEFINIR MÉTODOS O ACCIONES PARA ESTA CLASE
"""

class Persona:
    def __init__(self, nombreP, apellidosP, edadP):#1
        self.nombre = nombreP#ATRIBUTO PUBLICO
        self.apellidos = apellidosP#ATRIBUTO PUBLICO
        self.__edad = edadP#ATRIBUTO PRIVADO
    
    def get_edad(self):#2
        return self.__edad#GETTER DE LA EDAD, SIRVE PARA DEVOLVER LA EDAD
    
    def set_edad(self, nueva_edad):#3
        if nueva_edad > self.__edad:#SETTER DE LA EDAD, SIRVE PARA MODIFICAR LA EDAD
            self.__edad = nueva_edad
        else:
            print(f"No se puede tener menos anyos de los que tenías antes")

    def hablar(self):#4
        print(f"Hola yo soy {self.nombre} {self.apellidos} y tengo {self.get_edad()} anyos")#METODO HABLAR, QUE HACE UNA DETERMINADA ACCION


p = Persona("Alberto", "Canovas", 22)#LLAMADA AL CONSTRUCTOR DE UNA PERSONA, QUIERO CREAR UNA PERSONA P CON ESTOS VALORES
print(f"{p.nombre} {p.apellidos}")#COMO ESTOS DOS ATRIBUTOS SON PUBLICOS, PUEDO ACCEDER A ELLOS CON P.NOMATRIBUTO
print(f"Mi edad es de {p.get_edad()}")#COMO EL ATRIBUTO EDAD ES PRIVADO, NECESITO UN GETTER PARA ELLO. LLAMAMOS AL MÉTODO QUE NOS PROPORCIONA LA EDAD

p.nombre = "Felipe"
p.apellidos = "Marco Aurelio"
p.__edad = 23#ESTO NO FUNCIONA YA QUE ES UN ATRIBUTO PRIVADO
p.hablar()
p.set_edad(23)
p.hablar()

"""
A CONTINUACIÓN SE VA A DAR UNA EXPLICACIÓN DE LO QUE OCURRE EN ESTA CLASE: 
    1.DECLARAMOS UN CONSTRUCTOR QUE ES QUIEN VA A INICIALIZAR NUESTRA CLASE, ES DECIR, QUEREMOS QUE NUESTRA INSTANCIA PERSONA TENGA UN NOMBRE,APELLIDO Y UNA EDAD
        SE HACE CON __INIT__ ESTO INDICA QUE VAMOS A INICIALIZAR. LOS PARÁMETROS QUE HAY QUE PASARLE SIEMPRE SERÁN SELF, QUE INDICA QUE ES A ELLA MISMA Y LUEGO TODOS LOS QUE 
        QUERAMOS ANYADIR.
        ¡MUY IMPORTANTE! AL ANYADIR __ DELANTE DE UN ATRIBUTO, INDICA QUE ES PRIVADO Y QUE PARA ACCEDER A EL Y A SU VALOR HEMOS DE CREAR MÉTODOS ESPECIFICOS!
    2.MÉTODO ESPECIFICO QUE NOS DEVUELVE EL VALOR DE EDAD
    3.MÉTODO ESPEFICICO QUE MODIFICA EL VALOR DE EDAD
    QUE DIFERENCIA HAY ENTRE LOS ATRIBUTOS PUBLICOS Y LOS PRIVADOS, A LOS PUBLICOS PODEMOS ACCEDER SIN PROBLEMA Y  MODIFICAR SU VALOR DESDE FUERA DE LA CLASE(LÍNEAS 36 Y 37)
    SIN EMBARGO A LOS ATRIBUTOS PRIVADOS NO. LA IDEA DE MANTENER ATRIBUTOS PRIVADOS ES PODER MANTENER UNA INTEGRIDAD Y UNA LÓGICA DENTRO DE UNA CLASE. POR EJEMPLO:
        YO HE DECLARADO UNA PERSONA LLAMADA ALBERTO CANOVAS CON 22 AÑOS, SI YO QUISIERA MODIFICAR SU EDAD Y ESTE ATRIBUTO FUERA PUBLICO  YO PODRÍA PONER QUE TIENE -8 AÑOS
        COSA QUE NO TIENE SENTIDO, POR LO QUE PARA ESTOS CASOS DECLARANDO EDAD PRIVADA PUEDO CONTROLAR Y MEDIR UNA LÓGICA. EN MI CLASE SE CONTROLA QUE:
        SI ALBERTO TIENE 22 AÑOS Y QUEREMOS ACTUALIZAR SU VALOR PORQUE HA SIDO SU CUMPLEAÑOS, EVIDENTEMENTE VA A TENER MÁS AÑOS DE LOS QUE TENÍA ANTES, POR LO QUE VAMOS A CONTROLAR
        QUE LA NUEVA EDAD SEA MAYOR QUE LA EDAD QUE YA TENÍA Y ASÍ PODEMOS EVITAR ERRORES DE LÓGICA
    SI NOS FIJAMOS LA LÍNEA 36 Y 37 MODIFICAN LOS ATRIBUTOS NOMBRE Y APELLIDOS, EN CAMBIO LA 38 INTENTA PASAR DE 22 A 23 Y NO LO CONSIGUE. ESTO ES DEBIDO A QUE HAY QUE HACERLO MEDIANTE UN MÉTODO
    EN LA LINEA 40 LLAMO AL METODO ESPECIFICO PARA MODIFICAR LA EDAD, COMPRUEBA QUE TODO ES CORRECTO Y SE MODIFICA.
    4. METODO HABLAR, LAS PERSONAS PUEDEN HACER ACCIONES COMO HABLAR,COMER,DORMIR... NOSOTROS PODEMOS DECLARAR TODAS ESAS ACCIONES EN NUESTRA CLASE CON MÉTODOS. 
    EN ESTE CASO EL MÉTODO HABLAR HACE UNA PRESENTACIÓN DE LA PERSONA CON SU NOMBRE, APELLIDO Y EDAD
"""

#VEREMOS LA PROGRAMACIÓN ORIENTADA A OBJETOS MÁS EN PROFUNDIDAD Y CON TODAS SUS PROPIEDADES HERENCIA, REFLEXIÓN, POLIMORFISMO ETC...